### ISSUE TITLE
#83-Power Management - Review of power distribution board

### ISSUE THREAD

**Issue by cmucheru** [nakujaproject/n2_power_distribution_board#1]
Review the power distribution board.
@0x6f736f646f

**Comment by cmucheru** [comment]
Review the circuits for the voltage & current outputs.
- You can simulate the circuit(s) in Proteus.
- Duplicate to internship2022
 @FestusKioko

**Comment by SammyOina** [comment]
- Consider adding supercapacitors for the ejection charge.
- Please add a PDF to the repository for easy viewing on the browser
-  `AO3401A` might not be able to sustain the current draw of the BLDC motor at peak values of 10-12A
- Group and Label the sub-circuits

**Comment by cmucheru** [comment]
Update to schematic design. Check out for the p.d.f. under schematic folder. Is the super-capacitors  and the reverse protection circuits 1 & 2 okay? 
@Mike-Kimani 
@SammyOina 
@cmucheru
